//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YurtOtomasyonu.App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okul_Bolum
    {
        public int OkulId { get; set; }
        public int BolumId { get; set; }
    }
}
